### ISSUE TITLE
Custom maps (overall feature)

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-product-design#133]
### Overview
The custom maps will enable data-driven styling of markers and custom icons on the Akvo FLOW maps. This will expand the basic map functionality to the current FLOW maps and will give the users a chance to understand their collected data better in geographic context. We will implement this feature in separate steps, starting with the most basic functionality and supporting the simplest data structure, followed by tackling more complex items (as monitoring and repeated question groups for example). The users will be able to save their created maps and publish them on their website or share with other partners. 

The initial implementation will enable to base a map only on option questions per selected registration form. No custom icons will be supported and the user can only save the visualisations (no publishing). We will also add a set of permissions covering this new feature. 

Following implementations will tackle monitoring forms and repeated question groups.  

### Links to documents

**1st implementation - Functional design document** 
https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/133-Custom-maps/1st%20implementation%20-%20Functional%20design%20document.md

#### To do list and separate implementation parts and their relevant GH links

* [ ] 1st initial implementation (only rendering from registration forms - option questions, not supporting repeated question groups and monitored forms) 
   - https://github.com/akvo/akvo-product-design/issues/143
   - Mock ups: [Custom maps - 1st Implementation.pdf](https://github.com/akvo/akvo-product-design/files/64157/Custom.maps.-.1st.Implementation.pdf)
* [ ] add time range as a filter https://github.com/akvo/akvo-flow/issues/1628
* [ ] dealing with geotagged photos and videos https://github.com/akvo/akvo-product-design/issues/141
* [ ] supporting multi select options
* [ ] supporting option questions located in repeated question groups
* [ ] supporting monitored forms 
* [ ] show all points from the entire dashboard on the map (potential default map) - for users who have the right to see all data for all surveys
* [ ] use map as public map
* [ ] publish map functionality
* [ ] showing multiple geoshapes at once - basing a map on a geoshape question - https://github.com/akvo/akvo-flow/issues/1598

**Comment by janagombitova** [comment]
Mockups - 1st implementation 
[Custom maps - 1st Implementation.pdf](https://github.com/akvo/akvo-product-design/files/64144/Custom.maps.-.1st.Implementation.pdf)

**Comment by kymni** [comment]
The agreed action plan after a discussion with @jonase is to create a branch off [akvo-flow's issue 1407](https://github.com/akvo/akvo-flow/issues/1407). The technical discussion will therefore be kept on that issue's thread
A proof of concept for creating custom maps has already been made from which we can borrow some logic
A naming convention will need to be agreed on for naming of newly created maps

**Comment by kymni** [comment]
@janagombitova @jonase would it make sense to allow for flagging of different maps as either public or private such that maps flagged as public maps are visible all users whereas private maps are only visible to users based on their permissions?

**Comment by janagombitova** [comment]
@kymni and @jonase I think we should follow the current pattern of how we apply roles and permissions to maintain consistency and not confuse the users and how they expect things to work. If a user has 'View data' as a permissions and added to a folder, he can only select that one folder in the dropdown and thus only create a map based on that folder, or see a map created from that folder. 

However, we need to look into the options to decide to make one of the custom maps 'public' and show it in the public FLOW map (which is visible if you are not logged in). My thoughts were that this is something we can tackle in the following implementations.

**Comment by janagombitova** [comment]
I have reviewed the Functional design document in order to align the expected behaviour with the mockups from Webforms and Workflow where possible. As there is still quite some inconsistency in the FLOW dashboard I was aiming to at least align the new features that we will bring to give us a solid ground to start with.

https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/133-Custom-maps/1st%20implementation%20-%20Functional%20design%20document.md

@kymni can you please read through and make the needed changes?
@loicsans @Kiarii and @muloem Can you also please review the document and share your feedback? 

There are a few pending issues that still need some thought. They are quite small and I noted them all down in the Open issues part. We need to tackle them (make a decision) in order to move forward with the 1st implementation Charles is currently building. 

Loic and Charles can you please connect regarding the UI?

**Comment by janagombitova** [comment]
as this issue was eventually broken down into smaller issues and linked to them, I am closing this issue and the conversations can continue in the smaller issues.
