### ISSUE TITLE
Improve Flow app notifications

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-product-design#218]
@valllllll2000 to add more info

**Comment by valllllll2000** [comment]
The notifications need multiple improvements.

1) The icon has already been updated in this issue https://github.com/akvo/akvo-flow-mobile/issues/486
2) Notifications should be grouped by type when the android version allows it, issue https://github.com/akvo/akvo-flow-mobile/issues/468
3) When touching the notification, if the app is not opened we should open the app. For each notification we should decide which section of the app to open.
_4) Some notifications may be replaced by an error message via toast or dialog???_

**Comment by valllllll2000** [comment]
As promised when talking to @janagombitova here is a list of all the notifications in the app:
(the top entry is the title and second is subtitle).

When start bootstrap survey data from SD card
-> Loading survey data from SD card
-> Loading survey data from SD card

When done bootstrap survey data from sd card
-> Done loading data from SD card
-> Done loading data from SD card

When error bootstrap survey from sd card
-> Error processing bootstrap zip file
-> Error processing bootstrap zip file

When export data to sd card is complete
-> Data has been exported to SD card
-> form name

Error sending file (This form has been deleted in the dashboard, thus we cannot sync it)
-> "Form " + formId + " does not exist"
-> It has probably been deleted

Request missing files (images) in the datastore: when form was deleted
-> Form deleted
-> Form formName has been deleted

When synching files (progress)
-> Data Synchronization
-> Uploading data. Please, wait...

When synching files has ended
-> Data Synchronization
-> Synced Forms: %1$d - Failed: %2$d (if errors) or just Synced Forms: %1$d

When downloading forms
-> Downloading forms
-> Synced Forms: %1$d - Failed: %2$d if errors or just Synced Forms: %1$d

When synching datapoints:
-> Syncing Data Points...
-> Please wait

When synching datapoints (progress)
-> Syncing Data Points...
-> Synced %1$d Data Points

When done synching data points
-> Data Points Sync finished
-> Synced %1$d Data Points

When error synching data points due to a server error
-> Data Points Sync failed
-> Whatever is taken from the Excetion form the server!!!! (not good)
+++ a toast message is also displayed at the same time!!

When error synching data points due to a network error
-> Data Points Sync failed
-> Network Error
+++ a toast message is also displayed at the same time!!

**Comment by janagombitova** [comment]
Trying to make sense of how we use notifications and errors and to follow common Android patterns (https://material.google.com/patterns/errors.html#)

Initial thinking lives here: 
https://docs.google.com/spreadsheets/d/1ONmVlA9TYHCDEkglfWqIbJse64DNmOyhrl7fFwdEReU/edit#gid=0

**Comment by janagombitova** [comment]
@valllllll2000 I have added some suggestions to the spread sheet based on what I understood from the Google patterns advice. Lets talk about it together. 

Some things we should keep in mind: 
- make sure we use the same vocabulary for data points; surveys or forms
- need to decide if we will be talking about surveys or forms 
- unify how we call specific actions 
   - there is inconsistency in how we use the word "sync". Sometimes it refers to getting items onto the device and sometimes from the device out
   - use a different word to describe getting items onto the device and from the device 
   - we also mention the data point status in the list of points where we use: saved (for a submission that is not completed yet, user did not hit the submit button); exported (user hit the submit button but has no connection to sync); synced (submission reached the backend) - we should unify these words with the "notifications" 
- unify is we will talk about SD card storage or general storage 
- see how these changes will work on older dinosaur devices

**Comment by janagombitova** [comment]
After talking with @valllllll2000 today we have decided to take these changes in separate steps. We will first work on improving the current notifications that are handled by the **SurveyedDataPointSyncService** that inform the user about syncing data points (user triggered action in the menu to sync into the phone the data points for the selected surveys). The current notifications will change into loading icons and snackbars for errors (failed syncing).  

Second step will be handling actions related to a saved, submitted, synced form submission, which is part of the **DataSyncService**. Currently we show a notification informing about syncing and also inform the user in the status of each point by a changing icon and status text. We will leave the changing status icon and text and the notification will be removed.

**Comment by janagombitova** [comment]
We still need to figure out how to deal with notifications related to these services: 
- SurveyDownloadService
- BootstrapService 
- DataSyncService if actions fail

**Comment by janagombitova** [comment]
Today we looked at the **Bootstrap Service** and agreed to make three groups of changes: 

- investigate if it is possible for the app to check that there is a new surveys or a new version of a survey form without having the user to force close the app - https://github.com/akvo/akvo-flow-mobile/issues/635
- acknowledge that surveys are being loaded from the SD card using notifications - https://github.com/akvo/akvo-flow-mobile/issues/634
- add a visual indication of a new survey or new survey version in the menu drawer and list of surveys - https://github.com/akvo/akvo-flow-mobile/issues/636

**Comment by janagombitova** [comment]
Just to keep track of the remaining items: We still need to figure out how to deal with notifications related to these services:

- SurveyDownloadService
- DataSyncService if actions fail

**Comment by janagombitova** [comment]
Today we spoke about the **SurveyDownloadService** and agreed to use the same pattern as for the BoostrapService. We have however agreed to use toasts instead of notifications and use only toasts to indicate that the action has started or failed. Once forms are successfully downloaded we will show it by adding a dot to the menu icon and bold out the updated surveys in the list of surveys. 

More information can be found here: https://github.com/akvo/akvo-flow-mobile/issues/658 or in the issues linked above under the Bootstrap service 

The remaining notifications are for the DataSyncService if actions fail

**Comment by janagombitova** [comment]
All items are handled in separate issues in the Flow mobile repository and are being handled there (or already merged or being reviewed). If we missed any other items, we will handle them separately in the app repository. This change can be considered successfully completed

**Comment by janagombitova** [comment]
Here is a summary of all the groups of changes we aim to make with this issue and their relevant issues. Notifications around:  
* [x] syncing in data points https://github.com/akvo/akvo-flow-mobile/issues/583
* [x] syncing out submitted data https://github.com/akvo/akvo-flow-mobile/issues/584
* [ ] getting survey forms to the list from the SD card https://github.com/akvo/akvo-flow-mobile/issues/634
* [ ] getting survey forms in via an assignment https://github.com/akvo/akvo-flow-mobile/issues/658

All the other changes that came out of these discussion are listed in other comments above. The list of items here is related to notifications change

**Comment by muloem** [comment]
@janagombitova We have spoken about improving notifications for the online space.. should we add those here as well or a separate issue?

**Comment by janagombitova** [comment]
@Mulo separate. This is really looking at the app and I would not like mixing up the two. Will create a new one for the online space. I have the feeling we will also need to do a lot of slicing ;)

**Comment by janagombitova** [comment]
Completed
