### ISSUE TITLE
Improve structure of repeat question group exports

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-product-design#227]
# Who? 
Salim(s) and Petra(s) using only Excel to analyse the data. 

In some cases an external data expert is hired to clean and analyse the captured data. She uses more complex tools.   

# Why? 

## Problem 
Since the release of repeat question groups functionality we have received a lot of support requests and feedback around the structure of the raw data exports. 

Current export puts each repetition of the questions in a new row, with a column indicating the number of repetitions for that submission. The repeated rows hold the answer and number of repetition but no further links to the submission (as data point ID or more). All exports have the repeated column even though the form might not have any repeated groups

The main comments that arose are: 
- "I have to do much more manual work now, copying in IDs to link to rows before I can start analysing my data"
- "Because these are repeat questions the HH information does not get copied to each line of the repeat. Can this be done automatically or do I need to do it manually?" (Jenni from SNV) 
- if you are doing your analysis in the exported data Excel report and e.g. filter for a specific user, the repeated row stays at the bottom. Therefore you can’t really do a good analysis, because it belongs to another row. (feedback from West Africa hub)
- why do I have the Repeat No. column in my data even though I do not have any question group set to be repeated? 

# What? 

## Background 
The main reason we left the blank spaces was especially because this is meant to be "human readable" and that was a visual way to distinguish the data points that have RQG related data.

## Context

**What type of analysis do users do with data collected in repeated question groups?** 

**Is the analysis only on the repeated data or is it in relation to the entire data set?** 
- usually both, on the data in the groups itself, but also to relate it to answers in other questions

**How many repetitions do people make?** 
- there can me multiple groups in one form that are repeated and these can have a different number of repetitios
- I have seen up to 47 so far 
- can range vastly in one data set 

### from Jenni SNV 
https://drive.google.com/drive/folders/0B53AXQ5Y0VCMSmY2T3ZrMUFZTTA?usp=sharing

Here is some background information for the farmer raw data reports 
"In the famers spreadsheet the issue is that to do analysis at a HH level on repeat questions on crops (vegetables and fruit) cant do it without HH information being copied to each of the repeat lines. For example if I want to calculate total income per HH (as opposed to the total across all HHs and crops)"

"You can see in the attached I have had to copy the HH information to each line of repeat so I can generate the indicators by HH that are:
- All farmers(total production and production generating income)
- Female headed (total production and production generating income)
- Ethnic (total production and production generating income)
- Female farmer (total production and production generating income)

The other thing that would be of value is a HH total for previous questions. I have added in totals for some of the HHs at the right end of the data sheet to demonstrate (in red)."

### from Claire working with DNH Mali 

Based her feedback on dnhmali.akvoflow.org >Kayes > Fiche SAEP (Système d'Adduction d'Eau Potable) > Form "Enregistrement SAEP"

https://drive.google.com/file/d/0B53AXQ5Y0VCMbGFTU0p3M2FGVDA/view

### from Sae-Rom working with WPF Uganda 

wfp.akvoflow.org > 2017 surveys > Uganda > Flow 2017 > Uganda 2017 Core Public Institutions survey
https://drive.google.com/drive/folders/0B53AXQ5Y0VCMSmY2T3ZrMUFZTTA?zx=pnlrsr54kobz

## Ideas 
Solution ideas that came out of interviewing Akvo data analysts (Satya, Ethel, Karolina); external data scientists working with the West Africa hub (Claire); Geert's temporary Excel macro; and partner feedback via support: 
- Repetitions in new columns (questions repeated as well - not have 5 rows but 5 columns) but here you risk having many empty columns as the number of repetitions may vary 
- Repeated groups in separate sheets linked to the main dataset - can work nice but the user will have to combine the answers with the main data sets somehow anyway
- Repetitions combined on one cell (question once, all answers in the one cell) what gets complicated with more complex questions (as multiple options, cascades - how do you separate the multiple values and multiple repetitions?)
- Repetitions in separate rows but filling in all the metadata (as we do with monitoring) but here is the risk of duplicating results when analysing 

## To think of
- Should be keep the current layout but only add the data point name and create the new way and have the users to choose which export type they want to get? 
- Or should we just remove the current one and replace it with new? 
- Will this have any effect on the API users? 
- What should be do the the Repeat no. column for surveys with no repeated groups? 
- How will this affect data cleaning? 
- How will this affect adding new submissions to a survey via data cleaning? 
- Ho will this affect adding new repetitions to a survey via data cleaning? 

# Extra notes 
http://bit.ly/2iWqoO6
https://docs.google.com/document/d/1fq6D6P6EgF3SET4pafEFQ1Z4AzYaA2rp1oT7LUtxtps/edit

**Comment by janagombitova** [comment]
Friday we spoke with @muloem, @stellanl, @jonase and @Kiarii to talk about how to address this problem for Flow users, but also keeping Lumen user interaction in mind. 

We agreed on the following: 
- focus on our Excel users, not the more experienced data scientists needs, as they might even prefer a different form of export 
- we need to make a clear distinction between data export and the format used for data cleaning. Now the same structure is used for both what makes the technical implementation too complex and the data export overwhelming with information the user does not understand and use (question IDs, Instance number, etc)
- do not change one structure for another but allow users to choose which structure they want their export to have, but we need to know what the preferred one is to have a starting point 
- the lowest hanging fruit would be to fill in the missing meta data into the current export structure, but here we need to know if:
   - only meta data would suffice or all answers need to be filled in 
   - we need to see what implications this change would have on data cleaning and import 
- from the possible other structures we concluded: 
   - repeats in a cell: no go as the user will have to split the cell on her own, not solving the problem of extra manual steps needed
   - repeats in columns: benefit of having all answers in one row; we already split option in columns and cascades what will create even more columns but on the other hand is a rule we apply; you can end up with many empty columns; and for large surveys (with hundreds of questions) it will be hard to analyse
   - repeats in a separate sheet: benefit of keeping the current structure while creating a reference; harder to refer to the data in the main sheet; we can end up with many sheets if we export surveys where each sheet is a form for monitoring 

Next steps are: 
* [x] understand how our users analyse their data: What kind of analysis to people do? to prioritise which other export structure we can offer them
* [x] check what risks we run, if we add IDs to the currently empty cells (low hanging fruit)

**Comment by janagombitova** [comment]
From our last call we concluded also that the lowest hanging fruit would be to fill in the missing meta data into the current export structure. This can solve the problems users currently have (see above), address the complication of the overlap between exporting-analysing-cleaning, support the need to work with data offline, while we get time to explore, define, test out the more larger changes around the export structure.

We, however, did not specify whether we will copy in the empty rows: 
1. only the data point IDs (variable most commonly used by partners for filtering the data when cleaning and analysing it) 
2. all the meta data 
3. all the meta data and answers 

On the third option - all the meta data and answers - from user interviews we learned that: 
- it will make the analysis more confusing, as you might assume each row is a new submission and aggregating the data will give wrong results. 
- as the repetitions are now in separate rows, it will be hard to distinguish the number of repetitions visually, with only seeing it in the Repeat No. column

No clear answers were given in the interviews on the first and second option so we have created two example exports of the same dummy form **for A/B testing**. The A/B testing is done with Akvonauts who often clean and analyse Flow data for partners as part of the services we provide, Flow Advisory Group members, and partners who we know use repeated question groups from Flow support. Once the test is completed, the results will be shared here and a separate issue in flow repo will hold the implementation details.

**Comment by stellanl** [comment]
I'd like to re-raise a favorite subject of mine; we can easily add color or comments to cells in the report to indicate subtle things. There is even a facility to lock cells, which we could do with those that need to be unchanged for an import...

**Comment by janagombitova** [comment]
The initial discovery board can be found here: http://bit.ly/2iWqoO6

# Example of tasks Petra and Salim do
- Finding a specific data point 
- Finding duplicate entries 
- Filtering based on specific information (location, answers selected, etc). 
- Cleaning data based on column
- Aggregating results 
- Finding frequency
- Identifying total sample group and patterns in the group
- cluster variable per client
- Calculate total income per house hold and the total across all house holds and different crops
- Generate the indicators by household that are:
    * All farmers (total production and production generating income)
    * Female headed (total production and production generating income)
    * Ethnic (total production and production generating income)
    * Female farmer (total production and production generating income)

# Conclusions from A/B testing 
(end date is Wednesday 5pm, so will add more as they come in)

Total tests requested: 14 (9 Akvo and 5 users) 
Total requests received: 10
Choose Option A (only data point ID copied over): 1
Chose Option B (all meta data copied over): 9

## Summary of responses 
All responses can be found here: https://docs.google.com/document/d/14r2e89Lq385P4_PqdX7BwBWbin2Ym-QMczO5D1_XnDg/edit 

### Option A (1 vote) - only data point ID copied over
**For** 
- It was easier initially to pick out the duplicates with the naked eye
- Because empty cells from the second repetition (from column C) allow me to see clearly that I'm still on the same point without effort reading. So I provide less reading effort.

**Against**
- It took more manual clicks to achieve the same outcomes in filtering
- I also couldn’t filter based on the display name, which was particularly useful for analysis and cleaning on this specific dataset. 
- The large number of empty space to export data, puts the partner in a state of doubt,  feels that all data has not been exported.

### Option B (9 votes) - all meta data copied over

**For** 
- It gives me the opportunity to sort and filter for example on submission date. This is not possible when there are gaps in the metadata.
- When searching for a specific data point I was able to filter easily on Identifier, Display name, or instance, and all of the repeat question groups were displayed (didn’t have to cross reference manually).  
- For filtering on specific answers such as location I could easily use the display name, which was not possible with Option A. Also when filtering on specific answers (such as Boat/Ferry in column O) having all the metadata made it easy to find that datapoint.
- It has all meta data field filled out, making it less likely for people to confuse repetitions.
- Does not require a lot of data manipulation
- The number of empty spaces is reduced. This reassures the partner before any manipulation.
- With monitoring forms we also have the data point ID repeated for each submission and if I have repeated question groups in the monitoring form I use the Instance to filter and sort 

**Against**
- seems to me very cluttered for me to read easily, it asks me much more concentration so much more reading time.

## Next steps

As a first of many improvements to data exports we should ensure that regardless of the number of repetitions for one or many groups in a response we will copy over all the meta data in each row of the data export. By having all meta data copied over we ensure users can filter on data point ID or on instance number (used in case of monitoring forms with repeated groups as the data point IDs are no longer the unique representation of a submission) or on other info as submitter or date. 

I have created an issue in Flow's repository to add this change to Flow. @stellanl l will you be ok to pick it up? https://github.com/akvo/akvo-flow/issues/2247

# Colour coding and locking cells for cleaning 

@stellanl I really like the suggestion around colour coding as from the testing one of the commonly repeated issues users have is "that the data is hard to read" - hard to identify which group is repeated. 

As for locking cells, do you suggest to lock those that are not editable/importable with data cleaning? This will definitely help the users with the confusion some sometimes have, despite the description in support, that signatures, Caddisfly, instance, identifier are not editable columns. Let’s talk more. 

# Needs around RQGs and unresolved issues 
For all our users the current structure of exports of data with repeated question groups: 
- makes it hard to see how many submissions are there per form, so to understand their sample size 
- makes it impossible to see how many repetitions are per group, if more groups are repeated as the current Repeat no. column shows the largest number of repeats. But you can have three repeated groups where one is repeated twice, the second once and the thirds one seven times for a submission. 

Some users prefer: 
- to have repetitions per rows as it helps to aggregate data
- to have them in columns as it is the common format for importing in other tools, plus common rule - one row one submission - is respected 

---

**My personal note:** I think by trying to again create a “one export structure work for all” solution will not work. There are some decisions we can make for the users with regards to specific question types (options- where ‘other please specify’ is always in a separate column) but with repeated groups if we chose for one format or the other, there will always be an opposing user group, for whom we did not resolve the problem. 

I think we can, however, think of splitting the concerns - we can decide the rules and format for data cleaning and importing, but for analysing we let the user define how they want their data to look like in the sheet. 

---

Let’s discuss more in our next story mapping call @muloem @stellanl @Kiarii and @loicsans

**Comment by janagombitova** [comment]
In the session on 27th September with @muloem @stellanl and @Kiarii we came to the following conclusions 

# Setting the focus

We recognised two larger user groups who use, analyse, clean, store Flow data:  

**Group A**
    - use Excel to clean and analyse the data 
    - do not import the data to other tools and systems 
    - have general Excel understanding but no technical (development) skills 
    - need to have the data human readable and have it structured so they do not need to do too much manual processing 
    - prefer to have the repetitions in separate rows, as they can analyse the question answers per column, but prefer to have it in separate sheets to make it easier to work with and comprehend 

**Group B**
    - export the data to import it into other systems to store, clean and analyse 
    - need to have the dataset machine readable 
    - do not have the technical skill to set up the API but do not need to data export to necessarily be human readable 
    - need to have the rule of one submission is one row thus prefer repetitions to be in separate columns

We decided that we cannot solve the problems on the structure of the RQGs export for only one group of users, while not giving improvements to the other groups too. However, we cannot solve the problems for both groups at once. 

We will start with implementing the split of repetitions per sheet (Group A) as for them to analyse Flow data, the problem is of larger impact, the user group is larger and they to not have to tools and skills to process the current data export structure easily in comparison to Group B. Once the structure is implemented for Group A, we will move towards Group B. 

# Solution ideas

## Splitting repetitions into separate sheets 

This export will work for also importing back in, thus for data cleaning. 
It will replace the current Raw data reports.
It will be reused in the Raw data sheet given when exporting a Comprehensive report. 
   - thus in the comprehensive report will not hold two sheets - Raw data and Summary, but more depending on the number of repeated groups 
This structure will not be implemented on the raw data exports with advance settings.
   - the advance settings exports now differ from the "ordinary" raw data report exports by: 
      - creating separate columns for options 
      - splitting cascades into separate columns 
      - if defined, putting in the header for questions the user defined question ID and not the question name
      - omit Flow question IDs and the hash 
   - we agreed that we will keep the repetitions in rows and not have the split per sheet for this export type
   - this means, that Flow needs to keep repetitions in rows, but fill in all the meta data for all the rows too 

## Structure - separate sheets for repeated groups  
- add row to the top of the sheet (1st row) to indicate question groups: group number and name 
- keep the internal IDs needed for data cleaning (question ID, hash, etc) 
- 1st sheet will hold submission meta data, all question groups in order that are not repeatable 
- Repeat no. in the 1st sheet fully remove column 
- following sheets hold repeated groups - one sheet per repeated group if more than one repeated group in form 
- indicate in sheet name the Group number and name (?) 
- sheet with repeated group holds all meta data for submission, Repeat no. column and questions in the group.
    - can also have the new first row that shows the meta data and group number and name 

See example created by @stellanl during the call (holds dummy data)
[Split X-1.xlsx](https://github.com/akvo/akvo-product-design/files/1340064/Split.X-1.xlsx)


# Next steps 

We need to find a good way to name the file itself, the sheets, and the text in the email to make it clear on when you export data what you get. 

With the new UI designs we will test them out together with the export examples with user to validate our solution before going into production

**Comment by janagombitova** [comment]
# User testing 
We have finalised the user testing (did 5 interviews with different experienced Flow users) and validated that providing a sheet with RQGs split into different sheets and a second option when all the data is in one sheet and repetitions are in rows will help users who work with the data only in Excel as well as those importing it and using different tools for cleaning, analysing and visualising. 

UI mock ups: https://invis.io/2XDVONWNV#/257373554_1-a_Raw_ES
Notes for testing: http://bit.ly/2xStIkl

# Splitting repetitions to separate columns

In the user testing we have not validated this option as we decided to push it for later in the future. It is still a valid way of showing the data and we will consider it once the initial steps are done. 

# Next steps 
(also taking into consideration those mentioned above) 
* [x] All meta data copied over to all rows
* [x] Split groups to sheets - https://github.com/akvo/akvo-flow/issues/2278
* [x] Add group row to raw data exports https://github.com/akvo/akvo-flow/issues/2280
* [x] Ensure no of the file structure changes happen on raw data with Advanced settings -  no group row and no separate sheets for RQGs (stay in rows with all meta data copied over) - https://github.com/akvo/akvo-flow/issues/2281
* [x] Comprehensive report - remove the options to omit summaries and charts from the code - https://github.com/akvo/akvo-flow/issues/2284

**Comment by janagombitova** [comment]
Our job here is done with the 1.9.25 Yetanother Yak release. For the next steps around improvements check this issue: https://github.com/akvo/akvo-product-design/issues/273
