### ISSUE TITLE
Improve loading on Flow's dashboard

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-product-design#257]
Here is a list of actions users do where loading is visibly slow: 

**General**
* [x] initial loading  (add URL support to ember? or replace with react, use the in browser local storage, limit the number of unnecessary requests)
* [x] generating a report (minimise the number of requests we make for generating a report, threading model for the report generation, _side note_ notification of users)
* [x] device list (might be related to this https://github.com/akvo/akvo-flow/issues/2035) (serialisation and deserialisation, pagination of the devices list, number of devices retrieved in a single request)
* [x] user list 
* [x] loading of a form in the dropdown menus (in the Inspect data tab, Monitoring tab, Data cleaning tab and Export reports tab)
* [x] loading of answers in Inspect data tab (after selecting a submission form the list) (in some cases this has been caused by reloading of the questions, local storage)
* [x] loading of answers in Monitoring tab when viewing the specific form submissions 

**Survey creation and editing** 
* [x] for existing survey forms initial loading of questions (frequent time outs if more than 100 questions in form https://github.com/akvo/akvo-flow/issues/1442)
* [x] creating a new question group (https://github.com/akvo/akvo-flow/issues/2089)
* [x] creating a new question (https://github.com/akvo/akvo-flow/issues/2088)
* [x] saving a question after editing (https://github.com/akvo/akvo-flow/issues/2090)
* [x] creating a new empty folder, survey, form
* [ ] copying of a survey (does not appear in the page immediately (should we copy entities into a browser first and then POST?)
* [ ] copying of a question group (might be related to this issue though - https://github.com/akvo/akvo-flow/issues/1973

**Device request**
* [ ] syncing data points to a device (for refactor)
* [ ] device notification of missing files + required files (is there a way to improve the performance or limit the number of files sent to the devices)

**Comment by janagombitova** [comment]
I have played around two live instance and got these loading times: 

task | akvoflow-10 - heavy load, highest instance class | akvoflow-7 - heavy load, lowest class | low load, lowest class
--- | --- | --- | --- 
initial loading | 24,15s | | |
device list | | | | 
user list | | | |
report with many questions + options | | | |
form loading in Inspect data dropdown | | | |
answers in Inspect data | | | |
new folder | | | |
new survey | | | |
new form | | | |
new group | | | |
new question | | | |
saving option question | | | |
loading heavy load form (over 100 q) | | | |
copying survey | | | |
copying question group | | | |
copying question | | | |

**Comment by janagombitova** [comment]
*To do:  after 1.9.17 release run the same tests as above and compare results*

**Comment by janagombitova** [comment]
Update from @muloem on the changes introduced with 1.9.18 version: 

Regarding the question retrieval improvements worked on by Stellan and Valeria:
 
We have approximately halved the time to retrieve a list of questions for a form by eliminating some redundant queries. Instead of fetching questions group by group, we fetch all questions for a single form in one shot.  Since we have downgraded most instances to the lowest instance class, we'll should see the result of this by not having requests for a higher instance class. i.e. timeouts when retrieve form questions.
 
One change we pushed to the next release is still having considerable impact, i.e. ignoring the translations. For each option, of all the option questions in a survey, we make a query to retrieve the translation even though there is none.  This is about 15ms for each query (in some cases I have seen up to 100ms).  We'll see how that impacts on the performance when we merge with the translations code in the next release.
 
However, that said, the biggest portion of the performance lag is still with the spring framework so that has to join our list as a top priority to fix what is possible.
 
Regarding the reports generation mostly done by Stellan, there are quite some improvements. 
  - we retrieve questions in one batch (instead of by question group) to generate the raw data file header
  - in case we are generating the export version of the report, we have eliminated lots of redundant communication between Flow services and GAE, i.e for a survey with 20 option quesitons, we retrieve all options at once instead of making 20 separate requests to the backend
  - we eliminated an extra call where we were retrieving question information twice

**Comment by janagombitova** [comment]
## Performance tests round 2 - 1.9.17 version

I have ran the same tests defined above. Here are the results. I have not tested the copying tasks. 

task | akvoflow-10 - heavy load, highest instance class | akvoflow-7 - heavy load, lowest class | flowliberia-hrd - heavy load, lowest class | pilots.akvoflow low load, lowest class
--- | --- | --- | --- | ---
initial loading | 16,23s | 24,24s | 14,11s | 10,60s |
device list | 24,3s | 12,35s | 12,17s | 3,21s |
user list | 3,88s | 4,68s | 3,14s | 4,70s |
report with many questions/ responses | 1:33,75 | 49,40s | 16:04,46| 22,01s |
form loading in Inspect data dropdown | 0,47s | 14,40 | 0,70s| 0,98s |
submissions loading in Inspect data | 1,87s | 3,67s | 9,78s | 5,03 |
answers in Inspect data | 2,84s | 5,38s | 2,37s | 1,31s |
new folder | 6,30s | 1,57s | 2,57s | 2,80s |
new survey | 1,51s | 1,24s | 0,87s| 0,78s |
new form | 1,04s | 4,65s | 1,83s | 1,89s |
new group | 1,11s | 1,75s | 1,50s | 1,03s |
new question | 1,33s | 1,45s | 0,68s | 0,82s |
saving option question | 1,05s | 1,35s | 0,84s | 1,37s |
loading heavy load form (over 100 q) | 7,97s | 2,76s | 2,34s | 1,89s |

## Conclusions

**Comment by janagombitova** [comment]
## Performance tests round 3 - 1.9.18 version

task | akvoflow-10 - heavy load, highest instance class | akvoflow-7 - heavy load, lowest class | flowliberia-hrd - heavy load, lowest class | pilots.akvoflow low load, lowest class
--- | --- | --- | --- | ---
initial loading | 11,73s | 25,88s | 31,30s | 16,81s |
device list | 26,07s | 16,50s | 10,81s | 15,18s |
user list | 4,31s | 5,65s | 4,86s | 6,47s |
report with many questions/ responses | 1:52,18 | 58,26s | 15:37,27s | 31,87s |
form loading in Inspect data dropdown | 0,21s | 1,58 | 5,55s| 5,90s |
submissions loading in Inspect data | 1,27s | 5,19s | 4,00s | 3,78s |
answers in Inspect data | 2,17s | 6,75s | 1,76s | 1,55s |
new folder | 1,46s | 1,57s | 2,57s | 6,83s |
new survey | 1,01s | 0,89s | 0,87s| 2,13s |
new form | 0,84s | 2,06s | 1,83s | 2,68s |
new group | 0,41s | 0,71s | 1,50s | 0,70s |
new question | 1,16s | 0,59s | 0,68s | 2,31s |
saving option question | 0,59s | 0,61s | 0,84s | 0,77s |
loading heavy load form (over 100 q) | 1,59s | 2,34s | 2,34s | 0,59s |

*Note*: there are many factors that affect the loading, as how busy the instance is. This may vary from test to test, so these stats need to be taken as indications.

**Comment by janagombitova** [comment]
## Performance tests round 4 - 1.9.20 version

task | akvoflow-10 - heavy load, highest instance class | akvoflow-7 - heavy load, lowest class | flowliberia-hrd - heavy load, lowest class | pilots.akvoflow low load, lowest class
--- | --- | --- | --- | ---
initial loading | 8,16s | 7,04s | 16,29s | 21,48s |
device list | 22,08s | 11,28s | 14,26s | 9,60s |
user list | 4,61s | 4,23s | 3,78s | 3,71s |
report with many questions/ responses | 2:15,69 | 28,04s | 13:15,02s | 27,81s |
form loading in Inspect data dropdown | 0,21s | 1,58 | 1,78s| 17,38s |
submissions loading in Inspect data | 1,38s | 2,61s | 2,98s | 6,08s |
answers in Inspect data | 2,07s | 5,84s | 1,41s | 1,65s |
new folder | 1,27s | 2.03s | 3,05s | 5,41s |
new survey | 0,98s | 0,81s | 1,16s| 1,08s |
new form | 0,84s | 1,44s | 1,65s | 2,33s |
new group | 0,36s | 0,61s | 0,98s | 0,70s |
new question | 0,70s | 0,59s | 0,81s | 2,31s |
saving option question | 0,59s | 0,61s | 0,84s | 0,77s |
loading heavy load form (over 100 q) | 1,78s | 1,45s | 1,82s | 0,59s |

*Note*: there are many factors that affect the loading, as how busy the instance is. This may vary from test to test, so these stats need to be taken as indications.

**Comment by janagombitova** [comment]
Considering there are many factors that affect the loading time, we should take these statistics as indications of the results the changes, that we implemented made on the overall performance of the instances. All graphs calculate the loading time in seconds. 

# What were we aiming for
As a success we see: under 10s for loading of lists and under 2s for tasks as creating new items and saving changes. The ideal case would be under 5s loading of lists and under a 1s for creating new items. 

# Conclusions

This year our strategy is driven by allowing to scale. Secondly, we are working on decreasing the costs we have for running Flow currently. Improving loading time and overall performance will allow our partners to use Flow easily and in more projects. Slow loading calls result in more up time for each instance, then resulting in higher costs. If an instance times out, we have put it on the highest instance class to speed it up, but the highest class means higher costs. 

To see how the changes to the performance have improved overall loading and reduced costs we have looked at the ideal case for Flow, a heavy load instance (a lot of surveys, data, users, a lot of traffic) running on the lowest instance class (lowest cost per hour). From the stats we can conclude the following: 

## Improved 

From the list of actions we have been observing the loading time and trying to speed up we see an improvement for these items: 

### Overall instance loading
The overall instance loading has seen a rapid decrease in the last release going from almost 40s to 7s. Due to this improvement we have also started with deceasing the instance class from the remaining instances on the highest class.

![image](https://user-images.githubusercontent.com/12456965/27855157-ae49a888-6169-11e7-94ce-cd6ed7d79892.png)

### Loading of questions in a form, for forms over 100questions
One of the main reasons to increase an instance class for a partner instance is slow loading of questions in forms, resulting in a time out. We have decreased the loading time for this particular case from around 30s to 2s. 

![image](https://user-images.githubusercontent.com/12456965/27735862-e4577f2a-5da1-11e7-979a-cb3fef1bae47.png)

### Loading of user list 
The time to open and load the user list Decreased by 50%, from 8s to 4s. 

![image](https://user-images.githubusercontent.com/12456965/27735377-8207f7e8-5d9f-11e7-99c8-c4f0e403acfc.png)

### Loading of submissions per form in Data tab 

From the original 20s and more we have decreased the time it take to show the list of submission to the range of 3 to 2seconds. 

![image](https://user-images.githubusercontent.com/12456965/27735022-caf8e84c-5d9d-11e7-9cd1-ef26418e2e45.png)

## Stable 

Some of the tasks listed above have shown on our test case stable loading times, that are in the range we see as ok. This does not mean that we will not try to improve the speed. If we look at the other cases we tested, the loading time differs and can reach peaks.  For the actions listed here, we have not seen direct improvements on this one case. However, we will try to address them over time, but they do not require fixes in the next release.

Stable loading times are when the user is: 
- loading in forms in the Inspect data dropdown after selecting a survey
- loading in answers in the Inspect data tab after selecting a particular submission 
- creating a new folded, survey, form, question group and question
- saving changes 

## Still need attention

There are two main tasks that still need to be improved as their time to load is not good enough yet. 

### Device list

Even though the loading time for the device list is relatively stable, it still takes too long, above 10s. We will be addressing this issue in the next release. https://github.com/akvo/akvo-flow/issues/2035

![image](https://user-images.githubusercontent.com/12456965/27734971-9f54d282-5d9d-11e7-84a6-2660282dd7e3.png)

### Raw data export generation
The time it takes from the user asking for a report to receiving to in his email inbox depends on the size of the data. Smaller surveys are sent within a second, surveys with over 100 questions but not more than 1k submissions range from 50 to 40 seconds. But for truly large scale data, the user needs to wait up to 15 minutes. This is long as users start questioning if the raw data will even arrive. 

![image](https://user-images.githubusercontent.com/12456965/27735351-597f3e58-5d9f-11e7-878d-458a4180ad2f.png)

**Comment by janagombitova** [comment]
In the 1.9.21 release we pushed the last improvements regarding loading of devices in the Flow online space. With this change we moved all (but one) Flow instance back to the basic instance class. Instances were put on the highest class to resolve loading issues and avoid 500 errors. With the changes made over the last months we technically addressed the causes of slow loading. Thus moving the instances back to the basic class was the last step to do to see if the improvements made were successful or not. 

Below we compared the loading times of akvoflow-10 - heavy load instance - before all the changes made when on the highest instance class with the loading times today, after all the changes when on the basic class. 

task | on highest instance class | on the lowest instance class |
-- | -- | -- |
initial loading | 5,22 | 7,51 | 
device list | 25,2 | 23,30 |
user list | 4,21 | 5,70 |
report with many questions/ responses | 2:49,71 | 2:17,16 |
form loading in Inspect data dropdown | 1,47s | 1,01 |
submissions loading in Inspect data | 4,25s | 3,46 |
answers in Inspect data | 21,45s | 5,54 |
new folder | 7,07s | 2,75 |
new survey | 7,28s | 0,87 |
new form | 1,04s | 0,7 |
new group | 1,54s | 0,7 |
new question | 3,64s | 1,41 |
saving option question | 1,42s | 0,67 |
loading heavy load form (over 100 q) | 13,64 | 2,60 |

As we can see from the table above, the before and after numbers are comparable or improved. Thus the reasons for increasing the instance class are solved and our partners should not experience such issues anymore.

If any further issues come up around loading on Flow's space, we will tackle them individually.
