### ISSUE TITLE
Improve how users export data

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-product-design#273]
*Note: This issue is created based on an number of user interviews held over the last year to understand better how users use Flow's data exports, support issues and feature requests, discussions with Akvonauts who support users when it comes to cleaning and analysing data and on shared data sheets. All this research was then discussed with the team. 

The initial discovery board can be found here: http://bit.ly/2iWqoO6 This issue aims to summarise the discussion and set the next steps. 

# Context 

## Who
- Salim - interested in understanding the data captured for his region 
- Petra - analysing data for the entire programme 

We concluded in our last story mapping session that we focus on users who work with Excel and aim to resolve their issues. They need to be able to read the data sheet and understand what they see. 

### What do they do with the data? 
We know of two common user workflows: 

**Option A**
1. export data (Salim)
2. clean data offline (Salim for his region)
3. import data (Salim)
4. export cleaned data for analysis (Petra)

**Option B**
1. export data 
1.5 optional: import data into another tool
2. clean data offline
3. analyse data 
4. no more import 

**Example of tasks Petra and Salim do**

- Finding a specific data point 
- Finding duplicate entries 
- Filtering based on specific information (location, answers selected, etc). 
- Cleaning data based on column
- Aggregating results
- Finding frequency
- Identifying total sample group and patterns in the group
- Cluster variable per client
- Calculate total income per house hold and the total across all house holds and different crops that are captured in repeated groups 
- Generate the indicators by household that are: All farmers (total production and production generating income); Female headed (total production and production generating income); Ethnic (total production and production generating income); Female farmer (total production and production generating income)

### Current ways of exporting data in Flow 
Data exported in a different ways (structures) and their current use: 
- **raw data export** - also the file format for data cleaning 
   - used for cleaning data, for importing data and then re-exporting for analysis
   - used for cleaning data and analysing data with no importing back into Flow  
- **raw data export with advanced settings** - used for analysing data and importing it to other tools (not a known option to all users due to how it is hidden in the UI)
- **comprehensive report** - with graphs 

### Offline 

The 2nd largest value of being able to export data, after having access to your data, is **working offline**. Salim and Petra work in remote areas or with colleagues in areas with low connectivity, so being able to easily get their data out, clean it offline and analyse it offline is of great value to them. 

Being able to import the data back in helps to 1) make sure data is clean for future use and 2) to make sure all other Flow users work with the cleaned data in their analysis. We need to decide on how to deal with the current close link between the raw data exports and data cleaning. Either we need to strictly separate the two or find another solution. 
 
## Why

The data is only valuable once the users can use it, analyse and understand it and make decisions based on it. Flow users collect a vast amount of data in large forms and use mostly Excel to analyse their information. Some users also user other statistical programmes to analyse data. 

The currently most commonly used export file - raw data report - and its structure is not user friendly for the Excel users nor the advanced users. However, there is no one solution that fits all users as we can see from the different workflows they have and from the interviews done up till now.

# Problems and opportunities 

We want exports to be: 
- Fast
- Structure useful to most of the users, we will not make everyone happy but the 1st step should not be too tall
- Understandable and clear (you know what you get
- Supporting working offline 
- Name the file clearly (one way going file, two way going file)
- Save time and money
- Configurable - you can select what you want to export

In our first rounds of user story mapping sessions we have discovered that there are more areas to improve when it comes to exporting and then importing data. These are the larger problem areas we identified: 

## Export structure 
- overall our users have to learn to use Excel scripts, R and other tricks on how to make the file structure usable for them - we do not want our users to need to do the work we as a tool provider can do for them 
- Structure of repeated question groups - the largest problem users has 
   - different users use the sheet structure differently - if they want to use it in another tool they prefer repetition per column, for those analysing in Excel is to have repetition per row but in split sheets
- Tight connection between raw data export for cleaning and for analysing complicates our own implementation and how we can go about making changes 

## Orientation around report generation - "I do not know what I will get once I ask for this export"
- the language we use is unclear - how we describe things is messy, not easy to understand
- there is no one solution fits all users export structure 
- too late feedback on what she gets once she hits the export button 

## Unclear on progress
- Unclear on why data export did not arrive in their inbox, is it on its way? how long will it take? 
- Unclear on why an import fails or is it is still uploading, how long will it take? 
- when importing cleaned data or new data you have to go to a different page to see if it succeeded or not 

## Tracking and managing data collection (not data handling) 
- Many use raw data export to track progress of data collection - how many forms we submitted in a time frame, by which data collector, etc?
- Data collection black box - data is collected somewhere for some time, but you do not know where and for how much and how long - so users use the data export to resolve this problem

# Out of scope
In this issue we will not handle: 
- Solving the issue around tracking data collection progress - this will be handled in a separate issue 
- Improving comprehensive reports 
   - This is out of scope. We will not touch upon improving the comprehensive export at this moment of time. 
   - However, the comprehensive sheet currently holds the structure of the raw data export with advance settings and this needs to be addressed if we make changes to this export type. 
- Improving exporting geojson file types 
   - there is a minor improvement needed to this export option 
   - is handled in a separate issue here: 
 
# Next steps 

Focus on **How might we make a useful data export format for different users without affecting data cleaning rules?**  
- What is a useful data structure in sheets?
   - What can we enforce on users? 
   - What do the users need to select themselves? 
- How might we simply split data cleaning from analysing data?

**Comment by janagombitova** [comment]
I went through all my notes from interviews with users and Akvonauts, emails, support tickets and shared sheets to see if we can find patterns on how users transform the current raw data exports to make it cleanable and analysable. I have also summarised some extra requests and ideas we should consider for now or for in the future. 

Here are my conclusions:

# What is a useful data structure in sheets?

Here is a summary of changes our users currently make when analysing the current raw data export to prepare it for data cleaning and analysing: 

- Question name or variable name (current feature we call Question ID)
   - some prefer to use the question name and some the question ID 
   - we should let user choose which one they want to see 
   - users do not need the internal question IDs (numerical Flow created ones) - they are only needed by us when the user cleans data and imports it back to Flow (a common workflow to ensure cleaned data is available to all users) 
- Repeated question groups (more details here: https://github.com/akvo/akvo-product-design/issues/227) - user transform the structure in different ways:
   - some create separate sheets per groups -> analyse the data in the sheets 
      - repetition in rows (as now)  
       - with meta data in the beginning copied over for each repetition
   - some put the repetitions in separate columns -> mostly preferred for analysing Flow data in other tools, for more automatic analysis or for those used to this structure from other data collection tools
       - Q1-1 | Q2 - 1 | Q3 - 1 | Q1 - 2 | Q3 - 2 | Q3 - 2 | … 
       - what to show in Repeat No. column? 
   - repeated in rows but with meta data 
- Monitoring forms 
   - sometimes users need to export a monitoring form on its own (as now) 
   - sometimes user need to have data from registration forms in the monitoring export, so we should allow to merge in data from the registration form as they do it currently themselves manually 
   - some questions to consider: 
       - where should it merge in - in the end of the monitoring form data? in the beginning? 
       - should meta data and answers be repeated for each monitoring submission for one data point? 
       - how will a merged monitoring form with repeated groups with registration form with repeated groups look like? 
- Option question - bring some issues currently
   - show option name or show option code —> not need to show both 
       - some users remove the option name and some the code 
       - do not like to have both as it makes the data messy and requires an extra manual step in analysing the data 
   - split options per column for multiple select only
   - for single select it does not make sense to have all those extra columns, as I know there is only one possible answer 
   - always have ‘other please specify’ in a separate column
- Cascades - split in separate columns per level 

# Extra opportunities
- allow users to export all photos per form in a zip file 
- improve the export of a form structure (questions and options and settings in a more detailed way than now)
- allow to only export certain fields (columns) - I do not always need to see all the data, or for cases when I can combine a monitoring form with registration form I do not need to have all the registration form data, but only a few 
- form version saved with data and shown in export

@muloem @stellanl and @Kiarii I have tried to summarise some notes from our last story mapping session as well as from the previous user interviews and a few calls I had in the last weeks. Can you please go through these and your notes before our next session on improving data exports, so we are all on the same page? Thanks. Let's talk soon again .

**Comment by janagombitova** [comment]
# Decisions from 27 Sept meeting 

## Overall export improvement 

Together with @muloem @stellanl and @Kiarii we agreed to set the focus on: 

- **Who:** users using Flow data in Excel, with the path of export > clean > reimport data; who do NOT import  that data into another tool (database, analytical tool, etc); who work with the data with Excell skills thus it needs to be as human readable as possible and limit the number of steps users need to take 
- **What problem:** How might we improve the structure of data exports so it does not require the user to make too many manual steps to prepare the sheet for cleaning and analysing? 

As it is impossible to fix all problems around the export structure at once and validate them we agreed on this plan of action: 

### 1. Start with fixing the structure of repeated question groups

For the specification please check this issue:  https://github.com/akvo/akvo-product-design/issues/227

We aim to solve problems as: 
   - I do not know how many submissions are made for the form as there are too many empty rows and cells 
   - I do not know which group is repeated and how many times 
   - I cannot filter on data as for the repetitions I loose the links to the overall submission   

### 2. Improve the UI 

To make it clear and understandable that there are different export structures, one that works for data cleaning, one that is catered to import into other systems and how these two differ from each other

### 3. Add version number, the version of the form the submission was made against 

We discussed the risks of adding the version number to the data (creating the expectation that we can restore the form back to that version or to check that older form version for changes, what is currently not possible) versus the benefits (being able to see which submission was made against which form version to understand why there might be differences in the data) and decided that the benefits outweigh the risks. We do need to clearly explain what the version number means and what shortcomings there are. 

We agreed to add the version number to the submission meta data. We did not discuss the exact position of the column. This should be part of the meta data thus copied over all sheets and should not be editable (ignored in data cleaning and import)

@muloem @stellanl  and @Kiarii What are your thoughts on this one?

### 4. Ensuring we build the data export based on the last published version of the form

Now we base it on the current status of the form (not published is also a possibility). Building the exports on the last published version of the form,  allows us to have a more stable structure of data exports and allows us to know what is right when exporting the data. 

How will this affect the survey form export? 
   - exporting the form only
   - users use this functionality to “see” the surveys form before they send them to enumerators to cross check everything is set ok. Will this change then disrupt this use case? 

## Pushed for following iterations 

Later we will focus on improving other issues, listed below, as we need to make the above changes in order to address the ones below.  
   - structure option questions (split per column for multiple select option questions)
   - always have “other, please specify” in a separate column
   - split cascade level into separate columns 
   - add user defined question IDs (variable names) to data exports regardless of type of export
   - handle cases where registration data needs to be exported with the monitoring form data 

Other problems around data export will be handled once we resolve the above stated issues. The other problems are: 
   - You do not know when you will receive the export in your inbox, or how long it will take for the import to be completed 
   - Tracking data collection progress using data export 
   - etc

# Next steps 
0. release change where all meta data is filled in for all report types
1. Structure of RQGs  - See this issue for details: https://github.com/akvo/akvo-product-design/issues/227 
2. Improve UI
3. Adding version number 
4. Ensure export is based on last form published version

**Comment by janagombitova** [comment]
# User testing 
We have finalised the user testing (did 5 interviews with different experienced Flow users) and validated that providing a sheet with RQGs split into different sheets and a second option when all the data is in one sheet and repetitions are in rows will help users who work with the data only in Excel as well as those importing it and using different tools for cleaning, analysing and visualising. Users found the UI more clean and understandable and specific enough to make the decision on which export type they will choose based on the tasks they will do with the data

UI mock ups: https://invis.io/2XDVONWNV#/257373554_1-a_Raw_ES
Notes: http://bit.ly/2xStIkl

# Next steps update
(also taking a look at those mentioned above) 

We agreed to release incrementally what we have. We will start with making changes to the sheets while working on the UI as well. We might already release the changes to the sheets and then the UI. A larger communication will take place once the UI is out. 

**Here is a list of issues that we will handle in this first round.** 
* [x] Release change where all meta data is filled in for all report types 
* [x]  Structure of RQGs - See this issue for details: #227 (multiple small issues linked) 
* [x] Decide on names for different export types - https://github.com/akvo/akvo-flow/issues/2282
* [x] Improve UI - https://github.com/akvo/akvo-flow/issues/2282
* [x] Remove translations for exports https://github.com/akvo/akvo-flow/issues/2286
* [x]  Add collection date filter for Transformed data - https://github.com/akvo/akvo-flow/issues/2283

**The following improvements will contain changes as: (order of items still needs to be defined)** 
* [x] Improve email copy and file naming - https://github.com/akvo/akvo-flow/issues/1334
* [x] Add specification when last export was downloaded for raw data report - https://github.com/akvo/akvo-flow/issues/2288
* [ ] Show the file name in the UI prior to download (consider giving the option of users naming the files)
* [x] Adding version number to submissions (against which version of the survey form was this submission made) - https://github.com/akvo/akvo-product-design/issues/276
* [x] Split options to columns for only multiple select options (not all) and for cascades - https://github.com/akvo/akvo-flow/issues/2289 and adding separate column for other -  @https://github.com/akvo/akvo-flow/issues/2290
* [ ] Ensure export is based on last form published version - https://github.com/akvo/akvo-flow/issues/2285
* [ ] Validate the option to split repetitions in columns for cases on importing data to other tools

**Comment by janagombitova** [comment]
Most of the issue were already handles and released, other are added in Flow's repository.
